"""Independent pass predictions from Skyfield for the Go pass tests.

Run with Skyfield installed and the JPL DE421 kernel (de421.bsp) in the working
directory:

    python satellite/testdata/passes_skyfield.py > satellite/testdata/passes-skyfield.txt

Skyfield propagates the same element set with its own SGP4 binding, rotates to
the Earth-fixed frame with its own time scales, and decides sunlight from DE421.
"""
import sys
import skyfield
import sgp4
from skyfield.api import EarthSatellite, load, wgs84
from skyfield.searchlib import find_discrete

L1 = '1 25544U 98067A   26269.51782528  .00016717  00000-0  30306-3 0  9990'
L2 = '2 25544  51.6416 247.4627 0006703 130.5360 325.0288 15.49450470 12348'
SITES = [('denver', 39.74, -104.99), ('sydney', -33.87, 151.21)]

ts = load.timescale()
eph = load('de421.bsp')
sat = EarthSatellite(L1, L2, 'ISS', ts)
t0 = ts.utc(2026, 9, 26, 0, 0, 0)
t1 = ts.utc(2026, 9, 28, 0, 0, 0)

print('# ISS passes predicted by Skyfield %s (python-sgp4 %s, DE421) for the synthetic' % (skyfield.__version__, sgp4.__version__))
print('# element set in iss_python.json, 2026-09-26 00:00 to 2026-09-28 00:00 UTC, from the')
print('# geometric horizon, observers at 0 m on WGS84. Generated by passes_skyfield.py.')
print('#')
print('# Rows: <site> <lat> <lng> <rise utc> <peak utc> <set utc> <peak altitude deg>')
print('#       <shadow entry utc or -> <shadow exit utc or ->')
for name, lat, lng in SITES:
    topos = wgs84.latlon(lat, lng, elevation_m=0)
    times, events = sat.find_events(topos, t0, t1, altitude_degrees=0.0)
    passes = []
    cur = {}
    for t, ev in zip(times, events):
        if ev == 0:
            cur = {'rise': t}
        elif ev == 1 and 'rise' in cur:
            cur['peak'] = t
        elif ev == 2 and 'peak' in cur:
            cur['set'] = t
            passes.append(cur)
            cur = {}
    def lit(t):
        return sat.at(t).is_sunlit(eph)
    lit.step_days = 1.0 / 86400 * 20
    for p in passes:
        alt, _, _ = (sat - topos).at(p['peak']).altaz()
        tt, vv = find_discrete(p['rise'], p['set'], lit)
        entry = exit = '-'
        for t, v in zip(tt, vv):
            if not v and entry == '-':
                entry = t.utc_strftime('%Y-%m-%dT%H:%M:%S.%f')[:-3] + 'Z'
            if v and exit == '-':
                exit = t.utc_strftime('%Y-%m-%dT%H:%M:%S.%f')[:-3] + 'Z'
        f = lambda t: t.utc_strftime('%Y-%m-%dT%H:%M:%S.%f')[:-3] + 'Z'
        print('%s %.2f %.2f %s %s %s %.4f %s %s' % (name, lat, lng, f(p['rise']), f(p['peak']), f(p['set']), alt.degrees, entry, exit))
