// Package vsop87 evaluates the VSOP87 planetary theory: the series types the
// generated tables are written in, and the sum that turns a table into a
// heliocentric position. It holds no tables itself; each body's table lives in
// the package that needs it, so a program links only the tables it imports.
//
// The theory is P. Bretagnon and G. Francou, "Planetary theories in
// rectangular and spherical variables. VSOP87 solutions", Astronomy and
// Astrophysics 202, 309 (1988). Version D gives heliocentric ecliptic
// longitude, latitude, and radius referred to the dynamical ecliptic and
// equinox of date, in radians and astronomical units, as Poisson series in
// Julian millennia of TDB from J2000.0.
package vsop87

/*
MIT License

Copyright (c) 2026 Shane

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
*/

import "math"

// j2000 is the Julian date of J2000.0 and millennium the days in a Julian
// millennium, the unit of the time argument tau.
const (
	j2000      = 2451545.0
	millennium = 365250.0
)

// Term is one periodic term A cos(B + C tau), with A in radians or
// astronomical units, B in radians, and C in radians per Julian millennium.
type Term struct{ A, B, C float64 }

// Body holds the three VSOP87D variables of one body, each a list of series
// indexed by the power of tau that multiplies it. The tables are generated by
// internal/cmd/genvsop.
type Body struct {
	L, B, R [][]Term
}

// Heliocentric returns the body's heliocentric ecliptic longitude, in degrees
// in [0, 360), latitude in degrees, and radius vector in astronomical units, at
// the given Julian ephemeris day, referred to the dynamical ecliptic and
// equinox of date.
func (v *Body) Heliocentric(jde float64) (lonDeg, latDeg, radiusAU float64) {
	tau := Millennia(jde)
	l := Sum(v.L, tau)
	b := Sum(v.B, tau)
	r := Sum(v.R, tau)
	lonDeg = math.Mod(l*180/math.Pi, 360)
	if lonDeg < 0 {
		lonDeg += 360
	}
	return lonDeg, b * 180 / math.Pi, r
}

// Sum evaluates the sum over alpha of tau^alpha times the sum of
// A cos(B + C tau) over the terms of series[alpha], by Horner's rule in tau.
func Sum(series [][]Term, tau float64) float64 {
	var total float64
	for alpha := len(series) - 1; alpha >= 0; alpha-- {
		var s float64
		for _, t := range series[alpha] {
			s += t.A * math.Cos(t.B+t.C*tau)
		}
		total = total*tau + s
	}
	return total
}

// Millennia returns the Julian millennia from J2000.0 to the given Julian
// ephemeris day, the time argument tau of VSOP87.
func Millennia(jde float64) float64 {
	return (jde - j2000) / millennium
}
